### ISSUE TITLE
call me...

### ISSUE THREAD

**Issue by mervantanrikulu** [MohammadFneish7/WhatsappAgent#8]

**Comment by mervantanrikulu** [comment]
i think language problem

**Comment by mervantanrikulu** [comment]
OpenQA.Selenium.WebDriverTimeoutException: Timed out after 100 seconds

   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)

   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)

   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

   at WhatsappAgent.Messegner.WaitForQRAndLogin(UInt32 login_timeout) in C:\Users\96170\source\repos\WhatsappAgent\WhatsappAgent\Messagner.cs:line 100

   at WhatsappAgent.Messegner.Login(UInt32 login_timeout) in C:\Users\96170\source\repos\WhatsappAgent\WhatsappAgent\Messagner.cs:line 87

   at WhatsappAgentUI.Form1.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\96170\source\repos\WhatsappAgent\WhatsappAgentUI\Form1.cs:line 111

   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)

   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by MAKFneish** [comment]
??!
